### ISSUE TITLE
Installation Homer7 centos7 keeps failing

### ISSUE THREAD

**Issue by mveerdon** [sipcapture/homer-installer#75] opened 2020-12-31 10:37 UTC
Hi,
trying to install Homer7 on Centos7 server, using the homer-installer.

Homer-app keeps failing to run. Heplify-server is running.
In the homer-app.log I see connection errors.

Any ideas/tips howto solve this?

```
[opc@homer7 log]$  systemctl status homer-app
homer-app.service - Homer API Server and UI Webapplication
   Loaded: loaded (/usr/lib/systemd/system/homer-app.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-12-31 11:36:09 CET; 4s ago
  Process: 3733 ExecStart=/usr/local/bin/homer-app (code=exited, status=2)
 Main PID: 3733 (code=exited, status=2)

Dec 31 11:36:09 homer7 systemd[1]: Unit homer-app.service entered failed state.
Dec 31 11:36:09 homer7 systemd[1]: homer-app.service failed.
[opc@homer7 log]$
[opc@homer7 log]$
[opc@homer7 log]$  systemctl status heplify-server
heplify-server.service - HEP Server & Switch in Go
   Loaded: loaded (/usr/lib/systemd/system/heplify-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-12-31 11:31:04 CET; 5min ago
 Main PID: 3245 (heplify-server)
   Memory: 3.4M
   CGroup: /system.slice/heplify-server.service
           └─3245 /usr/local/bin/heplify-server -config=/etc/heplify-server.toml

Dec 31 11:31:04 homer7 systemd[1]: Started HEP Server & Switch in Go.
[opc@homer7 log]$ 

[opc@homer7 log]$ tail -10 homer-app.log
{"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-12-31T11:34:57+01:00"}
{"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-12-31T11:35:07+01:00"}
{"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-12-31T11:35:17+01:00"}
{"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-12-31T11:35:28+01:00"}
{"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-12-31T11:35:38+01:00"}
{"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-12-31T11:35:48+01:00"}
{"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-12-31T11:35:58+01:00"}
{"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-12-31T11:36:09+01:00"}
{"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-12-31T11:36:19+01:00"}
{"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-12-31T11:36:29+01:00"}
[opc@homer7 log]$ 
```

**Comment by aqsyonas** [comment] 2020-12-31 10:43
Hi,

Looks like your database is not up. You can start database by running below
command

systemctl restart postgresql-12 && systemctl enable postgresql-12 &&
systemctl status postgresql-12

Restart homer-app
systemctl restart homer-app && systemctl enable homer-app && systemctl
status homer-app

Br, Aqs

**Comment by mveerdon** [comment] 2020-12-31 10:48
```
[opc@homer7 log]$ sudo systemctl restart postgresql-12 && systemctl enable postgresql-12 && systemctl status postgresql-12
Job for postgresql-12.service failed because the control process exited with error code. See "systemctl status postgresql-12.service" and "journalctl -xe" for details.
[opc@homer7 log]$
[opc@homer7 log]$
[opc@homer7 log]$
[opc@homer7 log]$ systemctl status postgresql-12.service
postgresql-12.service - PostgreSQL 12 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-12.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2020-12-31 11:47:45 CET; 12s ago
     Docs: https://www.postgresql.org/docs/12/static/
  Process: 4357 ExecStartPre=/usr/pgsql-12/bin/postgresql-12-check-db-dir ${PGDATA} (code=exited, status=1/FAILURE)

Dec 31 11:47:45 homer7 systemd[1]: Starting PostgreSQL 12 database server...
Dec 31 11:47:45 homer7 systemd[1]: postgresql-12.service: control process exited, code=exited status=1
Dec 31 11:47:45 homer7 systemd[1]: Failed to start PostgreSQL 12 database server.
Dec 31 11:47:45 homer7 systemd[1]: Unit postgresql-12.service entered failed state.
Dec 31 11:47:45 homer7 systemd[1]: postgresql-12.service failed.
```

**Comment by mveerdon** [comment] 2021-01-03 13:49
Somebody any ideas?

**Comment by aqsyonas** [comment] 2021-01-04 07:55
looks like your postgresql could not start.

could you run journalctl -f -u postgresql-12 and restart postgresql-12 in
the second tab and see if you get some hints.

Br, Aqs

**Comment by mveerdon** [comment] 2021-01-04 09:05
Thanks,
but the output doesn't provide much info.

```
[opc@homer7 ~]$ sudo systemctl restart postgresql-12
Job for postgresql-12.service failed because the control process exited with error code. See "systemctl status postgresql-12.service" and "journalctl -xe" for details.
[opc@homer7 ~]$   

[opc@homer7 ~]$ sudo  journalctl -f -u postgresql-12
-- Logs begin at Mon 2021-01-04 10:02:18 CET. --
Jan 04 10:02:31 homer7 systemd[1]: Starting PostgreSQL 12 database server...
Jan 04 10:02:32 homer7 systemd[1]: postgresql-12.service: control process exited, code=exited status=1
Jan 04 10:02:32 homer7 systemd[1]: Failed to start PostgreSQL 12 database server.
Jan 04 10:02:32 homer7 systemd[1]: Unit postgresql-12.service entered failed state.
Jan 04 10:02:32 homer7 systemd[1]: postgresql-12.service failed.
Jan 04 10:04:34 homer7 systemd[1]: Starting PostgreSQL 12 database server...
Jan 04 10:04:34 homer7 systemd[1]: postgresql-12.service: control process exited, code=exited status=1
Jan 04 10:04:34 homer7 systemd[1]: Failed to start PostgreSQL 12 database server.
Jan 04 10:04:34 homer7 systemd[1]: Unit postgresql-12.service entered failed state.
Jan 04 10:04:34 homer7 systemd[1]: postgresql-12.service failed.
```

**Comment by mveerdon** [comment] 2021-01-05 09:29
@aqsyonas any ideas how to fix this?

**Comment by lmangani** [comment] 2021-01-05 10:08
You probably have too little memory or other resource constrictions failing the process. Check your system for errors.

**Comment by mveerdon** [comment] 2021-01-05 10:41
Thanks, any tips what's the best way to verify this?

**Comment by aqsyonas** [comment] 2021-01-05 10:46
Check if you have enough memory on the system

free -mh
enough disk space on system
df -h
and check if selinus is permissive mode or disabled.
sestatus

And check extended logs from postgresql by running below command after
restart of postgresql

journalctl -xe
Br, Aqs

**Comment by lmangani** [comment] 2021-01-14 09:53
@mveerdon do you still require assistance with this?

**Comment by mveerdon** [comment] 2021-01-14 10:37
I extended the VM.
disk space and memory looks okay.

This is the output of journal log

```
[opc@homer7 ~]$
[opc@homer7 ~]$ free -mh
              total        used        free      shared  buff/cache   available
Mem:            29G        1.3G         27G        8.6M        730M         27G
Swap:          8.0G          0B        8.0G
[opc@homer7 ~]$
[opc@homer7 ~]$
[opc@homer7 ~]$
[opc@homer7 ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         15G     0   15G   0% /dev
tmpfs            15G     0   15G   0% /dev/shm
tmpfs            15G  8.7M   15G   1% /run
tmpfs            15G     0   15G   0% /sys/fs/cgroup
/dev/sda3        39G  4.2G   34G  12% /
/dev/sda1       512M   12M  501M   3% /boot/efi
tmpfs           3.0G     0  3.0G   0% /run/user/994
tmpfs           3.0G     0  3.0G   0% /run/user/1000
[opc@homer7 ~]$
[opc@homer7 ~]$ sestatus
SELinux status:                 disabled
[opc@homer7 ~]$
[opc@homer7 ~]$ 


[opc@homer7 ~]$ journalctl -xe
Jan 14 11:35:51 homer7 homer-app[2754]: /app/main.go:719 +0x9d0
Jan 14 11:35:51 homer7 homer-app[2754]: main.main()
Jan 14 11:35:51 homer7 homer-app[2754]: /app/main.go:243 +0x21b
Jan 14 11:35:51 homer7 systemd[1]: homer-app.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 14 11:35:51 homer7 systemd[1]: Unit homer-app.service entered failed state.
Jan 14 11:35:51 homer7 systemd[1]: homer-app.service failed.
Jan 14 11:35:52 homer7 sudo[2761]:      opc : TTY=pts/0 ; PWD=/home/opc ; USER=root ; COMMAND=/bin/systemctl restart postgresql-12
Jan 14 11:35:52 homer7 sudo[2761]: pam_unix(sudo:session): session opened for user root by opc(uid=0)
Jan 14 11:35:52 homer7 polkitd[1002]: Registered Authentication Agent for unix-process:2762:56691 (system bus name :1.47 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object
Jan 14 11:35:52 homer7 systemd[1]: Cannot add dependency job for unit NetworkManager-wait-online.service, ignoring: Unit is masked.
Jan 14 11:35:52 homer7 systemd[1]: Starting PostgreSQL 12 database server...
-- Subject: Unit postgresql-12.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit postgresql-12.service has begun starting up.
Jan 14 11:35:52 homer7 postgresql-12-check-db-dir[2768]: "/var/lib/pgsql/12/data/" is missing or empty.
Jan 14 11:35:52 homer7 systemd[1]: postgresql-12.service: control process exited, code=exited status=1
Jan 14 11:35:52 homer7 postgresql-12-check-db-dir[2768]: Use "/usr/pgsql-12/bin/postgresql-12-setup initdb" to initialize the database cluster.
Jan 14 11:35:52 homer7 postgresql-12-check-db-dir[2768]: See /usr/share/doc/postgresql12-12.5/README.rpm-dist for more information.
Jan 14 11:35:52 homer7 systemd[1]: Failed to start PostgreSQL 12 database server.
-- Subject: Unit postgresql-12.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit postgresql-12.service has failed.
--
-- The result is failed.
Jan 14 11:35:52 homer7 systemd[1]: Unit postgresql-12.service entered failed state.
Jan 14 11:35:52 homer7 systemd[1]: postgresql-12.service failed.
Jan 14 11:35:52 homer7 polkitd[1002]: Unregistered Authentication Agent for unix-process:2762:56691 (system bus name :1.47, object path /org/freedesktop/PolicyKit1/Authenticati
Jan 14 11:35:52 homer7 sudo[2761]: pam_unix(sudo:session): session closed for user root
Jan 14 11:35:59 homer7 influxd[1778]: [httpd] ::1 - - [14/Jan/2021:11:35:59 +0100] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.17.0 Go/1.15.5" 4a9824c7-5654-11eb-8
Jan 14 11:36:02 homer7 systemd[1]: homer-app.service holdoff time over, scheduling restart.
Jan 14 11:36:02 homer7 systemd[1]: Cannot add dependency job for unit NetworkManager-wait-online.service, ignoring: Unit is masked.
Jan 14 11:36:02 homer7 systemd[1]: Stopped Homer API Server and UI Webapplication.
-- Subject: Unit homer-app.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit homer-app.service has finished shutting down.
Jan 14 11:36:02 homer7 systemd[1]: Started Homer API Server and UI Webapplication.
-- Subject: Unit homer-app.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit homer-app.service has finished starting up.
--
-- The start-up result is done.
Jan 14 11:36:02 homer7 homer-app[2773]: {"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2021-01-14T11:36:02+01:00"}
Jan 14 11:36:02 homer7 homer-app[2773]: panic: failed to connect database
Jan 14 11:36:02 homer7 homer-app[2773]: goroutine 1 [running]:
Jan 14 11:36:02 homer7 homer-app[2773]: main.getConfigDBSession(0xc00036ce20)
Jan 14 11:36:02 homer7 homer-app[2773]: /app/main.go:719 +0x9d0
Jan 14 11:36:02 homer7 homer-app[2773]: main.main()
Jan 14 11:36:02 homer7 homer-app[2773]: /app/main.go:243 +0x21b
Jan 14 11:36:02 homer7 systemd[1]: homer-app.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 14 11:36:02 homer7 systemd[1]: Unit homer-app.service entered failed state.
Jan 14 11:36:02 homer7 systemd[1]: homer-app.service failed.

[opc@homer7 ~]$     
```

**Comment by aqsyonas** [comment] 2021-01-14 10:43
Hey,


Looks like the database was not initialized as pointed out by the below
line.

"/var/lib/pgsql/12/data/" is missing or empty.

You can initialize it by using the below command.
service postgresql initdb
service start postgresql

You might need to re-create the required databases and tables by following
the below instructions.

https://github.com/sipcapture/homer-app

Br, Aqs

**Comment by mveerdon** [comment] 2021-01-14 10:53
```
[opc@homer7 homer]$ service start postgresql
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.
[opc@homer7 homer]$  
```

**Comment by mveerdon** [comment] 2021-01-14 11:16
trying to re-created the DB via the github instructions. But looks like my Homer installation is not in the expected folder

```
[opc@homer7 homer]$
[opc@homer7 homer]$ ./homer-app -webapp-config-path=/etc
-bash: ./homer-app: No such file or directory
[opc@homer7 homer]$
[opc@homer7 homer]$
[opc@homer7 homer]$ ls -lrt
total 4
drwxr-xr-x. 3 root root 4096 Dec 23 16:27 dist
drwxr-xr-x. 2 root root   62 Jan 14 11:52 etc
drwxr-xr-x. 2 root root  258 Jan 14 12:15 log
[opc@homer7 homer]$
[opc@homer7 homer]$ 
```

**Comment by aqsyonas** [comment] 2021-01-14 11:45
Check if your postgresql is up and running before you try to create tables.

service status postgresql-12

you can find the homer-app binary by running below command.

which homer-app
/usr/local/bin/homer-app

 /usr/local/bin/homer-app   -create-table-db-config
 /usr/local/bin/homer-app   -populate-table-db-config

Br, Aqs

**Comment by mveerdon** [comment] 2021-01-14 12:27
the first step goes wrong

```
[opc@homer7 homer]$ service status postgresql-12
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.
[opc@homer7 homer]$ 
```

**Comment by lmangani** [comment] 2021-01-14 15:40
adjust... 
` systemctl status postgres-12`

**Comment by mveerdon** [comment] 2021-01-14 15:43
```
[opc@homer7 ~]$ systemctl status postgres-12
Unit postgres-12.service could not be found.
[opc@homer7 ~]$
[opc@homer7 ~]$ 
[opc@homer7 ~]$ sudo service postgresql initdb
Hint: the preferred way to do this is now "postgresql-setup initdb"
Data directory is not empty!

[opc@homer7 ~]$  
```

**Comment by mveerdon** [comment] 2021-01-19 07:12
Hi @aqsyonas  any ideas howto solve this postgres-12 error (of my last post)?

**Comment by CoderJoeW** [comment] 2021-01-20 14:53
This is also broken for me brand new minimal centos 7 install plenty of memory/disk/cpus seems to me that the installer is broken

**Comment by lmangani** [comment] 2021-01-20 15:50
@flaminggenius what is consuming the memory/disk/cpu exactly? please post some details. The installer is definitely not the issue if we're talking about load, perhaps rather about optimizing the settings (no magic)

**Comment by CoderJoeW** [comment] 2021-01-20 17:11
@lmangani  you misunderstand what I was saying a brand new centos 7 out if the box no load issues

This installer fails

It is broken


Please create a new centos 7 minimal install and try to run installer

**Comment by lmangani** [comment] 2021-01-20 17:46
Ok. Please attach your logs if that's the case

**Comment by CoderJoeW** [comment] 2021-01-20 18:06
Steps to reproduce

1. Install VM with new centos 7 minimal install
2. Run  yum install redhat-lsb-core epel-release curl wget git -y
3.  yum upgrade -y
4. reboot
5. cd /usr/src
6. wget https://github.com/sipcapture/homer-installer/raw/master/homer_installer.sh
7. chmod +x homer_installer.sh
8. ./homer_installer.sh 


As mentioned by the OP it seems that the installer is failing because of something to with postgresql

Attaching the log output from following the exact steps listed above

[homer_installer.sh.8110.log](https://github.com/sipcapture/homer-installer/files/5844384/homer_installer.sh.8110.log)

**Comment by CoderJoeW** [comment] 2021-01-20 18:06
@lmangani

**Comment by CoderJoeW** [comment] 2021-01-20 20:25
Hello @mveerdon @lmangani 

I have found a way to force it through

You must be on a clean install(meaning you have not run the installer yet

Find the line that says 

local cmd_locatepostgre="$(locate postgresql-12-setup)"

Replace this with 

local cmd_locatepostgre="/usr/pgsql-12/bin/postgresql-12-setup"

Run the installer and it will work

I don't specifically know why it is not working but the command 

locate postgresql-12-setup

returns

/usr/bin/postgresql-12-setup
/usr/pgsql-12/bin/postgresql-12-setup


I suppose because 2 different versions are being returned is why it does not work? I am not sure  but I have verified that the above will force it through

**Comment by mveerdon** [comment] 2021-01-21 08:16
Is there a way to 'wipe' my Centos installation to a fresh start point?

**Comment by aqsyonas** [comment] 2021-01-21 08:21
You would need to restart OS on your server for this.

Br, Aqs

**Comment by CoderJoeW** [comment] 2021-01-21 22:40
@mveerdon If you had previously run the installer you will need to completely reinstall the OS 

@lmangani  Anybody currently interested in fixing the installer?

**Comment by lmangani** [comment] 2021-01-21 23:07
@flaminggenius absolutely that's why we're here. @aqsyonas could you check this out w/ the team?

**Comment by CoderJoeW** [comment] 2021-01-21 23:15
@lmangani Appreciate it.

**Comment by aqsyonas** [comment] 2021-01-22 10:42
@CoderJoeW @lmangani sure, i will check this.

**Comment by aqsyonas** [comment] 2021-02-01 10:11
@CoderJoeW could you please take the latest installer script, issue should be fixed now.  
Thanks for the report.

**Comment by mveerdon** [comment] 2021-02-25 08:45
@CoderJoeW @lmangani want to try to re-install OS and Homer7 again.

What are the minimal OS specs to run Homer7 on a VM?

**Comment by CoderJoeW** [comment] 2021-02-26 16:45
@mveerdon  I don't think there are official recommended specs. I think it will depend largely on the amount of traffic sent to homer. If not much traffic then a 2 core 4GB ram centos7 machine should be fine

@aqsyonas  Will give it a shot when I get a chance

**Comment by mveerdon** [comment] 2021-03-15 16:34
Hi,
I have Homer7 now running on a new Centos7 VM server.

Trying to setup that my Oracle SBC are sending syslog data into Homer. Try to find the right config and information how to do it.

Any advices?

**Comment by CoderJoeW** [comment] 2021-03-15 17:00
@mveerdon  Probably not gonna get much help with that here and its a bit off topic. 

Maybe try here: https://groups.google.com/g/homer-discuss


@aqsyonas  Installer works fine I believe this issue can be marked as fixed

**Comment by lmangani** [comment] 2021-03-15 17:08
@CoderJoeW thanks for helping out! @mveerdon the answer is horaclifix but its not part of the official project, for obvious reasons

**Closed as completed by lmangani** 2021-03-15 17:08 UTC

**Comment by mveerdon** [comment] 2021-03-16 08:38
Thanks for this info & the support!
